openapi: 3.0.0
info:
  version: "1"
  title: marv
security: [{}]
paths:
 /test1:
   post:
    responses: {
        "200": {
          description: "200 ok response"}
    }
    x-amazon-apigateway-api-key-source: AUTHORIZER
    x-amazon-apigateway-auth: NONE
    x-amazon-apigateway-integration:
      httpMethod: "POST"
      passthroughBehavior: "when_no_match"
      type: "AWS_PROXY"
      uri: """