name: Pulumi_Pull_Request_Go
on:
  - pull_request
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.16']
        go-example: ['azure-go-resourcegroup', 'azure-go-sqlserver-loganalytics', 'azure-go-subscriptionid-from-resourcegroup', 'azure-go-sqlserver-servervulnerabilityassessment']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: go mod download
        working-directory: ${{ matrix.go-example }}
      #- name: Install Pulumi CLI
      #  uses: pulumi/setup-pulumi@v2
      #- name: Configure AWS Credentials
      #  uses: aws-actions/configure-aws-credentials@v1
      #  with:
      #    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #    aws-region: ${{ secrets.AWS_REGION }}
      #    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dev
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          work-dir: ${{matrix.go-example }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          #GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}
          ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
          ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
          ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
          ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
