name: Pulumi_Pull_Request_Typescript_Azure
on:
  - pull_request
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16.x']
        typescript-example: ['azure-ts-consumption-budget', 'azure-ts-datafactory', 'azure-ts-iac-workshop-lab1', 'azure-ts-jenkins', 'azure-ts-keyvault-appservice', 'azure-ts-managedinstance', 'azure-ts-resourcegroup-fixname', 'azure-ts-serverless-http-trigger', 'azure-ts-serverless-www-html',
                             'azure-ts-sqlserver-loganalytics', 'azure-ts-sqlserver-servervulnerabilityassessment', 'azure-ts-sqlserver', 'azure-ts-subscriptionid-from-resourcegroup', 'azure-ts-synapse-workspace']
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
        working-directory: ${{ matrix.typescript-example }}
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dev
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          work-dir: ${{ matrix.typescript-example}}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
          ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
          ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
          ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
