name: Pulumi_Pull_Request_Python_GCP
on:
  - pull_request
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9.x']
        python-example: ['google-native-py-network-postgres-function']
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          echo "python3 venv setup"
          python3 -m venv venv
          echo "python3 source activate"
          source venv/bin/activate
          echo "python pip3 install"
          pip3 install -r requirements.txt
        working-directory: ${{ matrix.python-example }}
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dev
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          work-dir: ${{matrix.python-example }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}
