name: Pulumi_Pull_Request_Typescript_Azure
on:
  - pull_request
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16.x']
        typescript-example: ['azure-ts-synapse-workspace', 'azure-ts-sqlserver', 'azure-ts-datafactory', 'azure-ts-managedinstance', 'azure-ts-jenkins', 'azure-ts-serverless-http-trigger', 'azure-ts-resourcegroup-fixname', 'azure-ts-iac-workshop-lab1',
                             'azure-ts-sqlserver-loganalytics', 'azure-ts-keyvault', 'azure-ts-subscriptionid-from-resourcegroup', 'azure-ts-consumption-budget', 'azure-classic-ts-datalakegen2', 'azure-ts-sqlserver-servervulnerabilityassessment', 'azure-ts-serverless-www-html', 'azure-classic-ts-datafactory']
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2
      - run: npm install
        working-directory: ${{ matrix.typescript-example }}
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dev
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          work-dir: ${{ matrix.typescript-example}}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}
          ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
          ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
          ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
          ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
