name: Pulumi_Pull_Request_Python_AWS
on:
  - pull_request
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8.x']
        python-example: ['aws-classic-py-vpc-quickstart', 'aws-classic-py-beanstalk', 'aws-classic-py-eks-spot-mg', 'aws-classic-py-s3-staticwebsite', 
        'aws-classic-py-apigateway-lambda-serverless', 'aws-classic-py-dynamodb', 'aws-classic-py-vpc', 'aws-classic-py-eks-spot-nodegroups', 'aws-classic-py-get-ami', 
        'aws-classic-py-get-regions','aws-classic-py-aws-load-balancer-controller-helm-release']
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2
      - run: pip install -r requirements.txt
        working-directory: ${{ matrix.python-example }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dev
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          work-dir: ${{matrix.python-example }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}
          ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
          ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
          ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
          ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}