name: Pulumi_Pull_Request_Python_AWS2
on:
  - pull_request
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9.x"]
        python-example:
          [
            "aws-classic-py-multiple-ec2-ebs",
          ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pulumi aws plugin and setup python env
      - run: |
          echo "python3 venv setup"
          python3 -m venv venv
          echo "python3 source activate"
          source venv/bin/activate
          echo "Re-installing aws plugins"
          echo "python pip3 install"
          pip3 install -r requirements.txt
          pulumi plugin rm resource aws -a -y
          pulumi plugin install resource aws
        working-directory: ${{ matrix.python-example }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dev
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          work-dir: ${{matrix.python-example }}
          refresh: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
