name: Pulumi_Pull_Request_Python_AWS
on:
  - pull_request
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9.x"]
        python-example:
          [
            "aws-classic-py-vpc-quickstart",
            "aws-classic-py-beanstalk",
            "aws-classic-py-eks-spot-mg",
            "aws-classic-py-s3-staticwebsite",
            "aws-classic-py-apigateway-lambda-serverless",
            "aws-classic-py-dynamodb",
            "aws-classic-py-vpc",
            "aws-classic-py-eks-spot-nodegroups",
            "aws-classic-py-get-ami",
            "aws-classic-py-get-regions",
            "aws-classic-py-aws-load-balancer-controller-helm-release",
            "aws-classic-py-vpc-msk-kafka-client",
          ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup python env
        run: |
          echo "python3 venv setup"
          python3 -m venv venv
          echo "python3 source activate"
          source venv/bin/activate
          echo "python pip3 install"
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
        working-directory: ${{ matrix.python-example }}
      - name: Install Pulumi AWS resource provider plugins
        run: pulumi plugin install resource aws v5.4.0 --non-interactive --reinstall
        working-directory: ${{ matrix.python-example }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dev
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          work-dir: ${{matrix.python-example }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
