name: Pulumi_Pull_Request_Typescript_AWS_plugin
on:
  - pull_request
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16.x']
        typescript-example: ['aws-classic-ts-vpc-get-zones-awsx', 'aws-classic-ts-vpc-natgatway-strategy'
                             ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: npm install
        working-directory: ${{ matrix.typescript-example }}
      - name: Install Pulumi AWS resource provider plugins
        run: pulumi plugin install resource aws v5.4.0 --non-interactive --reinstall
        working-directory: ${{ matrix.typescript-example }}  
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dev
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          work-dir: ${{ matrix.typescript-example}}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
