name: Pulumi_Push_Request_Python
on:
  push:
    branches:
      - master
      - main
jobs:
  up:
    name: Update
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8.x']
        python-example: ['aws-ts-vpc-with-ecs-fargate-py/ecs-fargate-python']
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2
      - run: pip install -r requirements.txt
        working-directory: ${{ matrix.python-example }}
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: dev
          work-dir: ${{ matrix.python-example }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}
          ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
          ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
          ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
          ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}